---
version: 1
dependencies:
  galaxy: _build/requirements.yml
  python: _build/requirements.txt
  system: _build/bindep.txt
additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    - ADD certs /etc/pki/ca-trust/source/anchors
    - RUN update-ca-trust
    - ENTRYPOINT []
    - ENV SHELL /bin/bash
