name: Build and Push latest image

on:
  push:
    # build and push anytime commits are merged to main
    branches:
      - main
  schedule:
    # build every month
    - cron: '0 0 2 * *'

jobs:
  build_and_push_latest:
    runs-on: ubuntu-latest
    name: Build and push latest tag from devel and on new commits
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker -- --tag=quay.io/lumarel/ee-lint:latest

      - name: Push images
        run: |
         echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
         docker push quay.io/lumarel/ee-lint:latest

  build_and_push_latest-stable-2_11:
    runs-on: ubuntu-latest
    name: Build and push stable-2.11 tag from devel
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker-stable-2.11 -- --tag=quay.io/lumarel/ee-lint:stable-2.11

      - name: Push images
        run: |
         echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
         docker push quay.io/lumarel/ee-lint:stable-2.11

  build_and_push_latest-stable-2_12:
    runs-on: ubuntu-latest
    name: Build and push stable-2.12 tag from devel and on new commits Ansible 2.12
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker-stable-2.12 -- --tag=quay.io/lumarel/ee-lint:stable-2.12

      - name: Push images
        run: |
         echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
         docker push quay.io/lumarel/ee-lint:stable-2.12

  build_and_push_latest-non_runner:
    runs-on: ubuntu-latest
    name: Build and push nr-latest tag from devel and on new commits
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker-nr -- --tag=quay.io/lumarel/ee-lint:nr-latest

      - name: Push images
        run: |
         echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
         docker push quay.io/lumarel/ee-lint:nr-latest

  build_and_push_latest-non_runner-stable-2_11:
    runs-on: ubuntu-latest
    name: Build and push nr-stable-2.11 tag from devel
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker-nr-stable-2.11 -- --tag=quay.io/lumarel/ee-lint:nr-stable-2.11

      - name: Push images
        run: |
         echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
         docker push quay.io/lumarel/ee-lint:nr-stable-2.11

  build_and_push_latest-non_runner-stable-2_12:
    runs-on: ubuntu-latest
    name: Build and push nr-stable-2.12 tag from devel and on new commits Ansible 2.12
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker-nr-stable-2.12 -- --tag=quay.io/lumarel/ee-lint:nr-stable-2.12

      - name: Push images
        run: |
         echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
         docker push quay.io/lumarel/ee-lint:nr-stable-2.12
