---

name: CI

on:
  pull_request:
    branches: [main]

jobs:
  podman-ansible-box:
    runs-on: ubuntu-latest
    name: Podman ansible-box image
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          podman build . --file Containerfile-ansible-box

  docker-ansible-box:
    runs-on: ubuntu-latest
    name: Docker ansible-box image
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build . --file Containerfile-ansible-box
