---

name: CI

on:
  pull_request:
    branches: [main]

jobs:
  podman:
    runs-on: ubuntu-latest
    name: Podman
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build EE with Podman
        run: |
          tox -e podman

  docker:
    runs-on: ubuntu-latest
    name: Docker
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build EE with Docker
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker

  podman-ansible-box:
    runs-on: ubuntu-latest
    name: Podman ansible-box image
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          podman build . --file Containerfile-ansible-box

  docker-ansible-box:
    runs-on: ubuntu-latest
    name: Docker ansible-box image
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build . --file Containerfile-ansible-box
