name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker -- --tag=quay.io/lumarel/ee-lint:${{ github.event.release.tag_name }}

      - name: Apply latest tag
        run: |
         docker tag quay.io/lumarel/ee-lint:${{ github.event.release.tag_name }} quay.io/lumarel/ee-lint:latest

      - name: Push images
        run: |
         echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
         docker push quay.io/lumarel/ee-lint:${{ github.event.release.tag_name }}
         docker push quay.io/lumarel/ee-lint:latest

  release-stable-2_11:
    runs-on: ubuntu-latest
    name: Release Ansible 2.11
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker-stable-2.11 -- --tag=quay.io/lumarel/ee-lint:stable-2.11

      - name: Apply latest tag
        run: |
         docker tag quay.io/lumarel/ee-lint:stable-2.11 quay.io/lumarel/ee-lint:${{ github.event.release.tag_name }}-stable-2.11

      - name: Push images
        run: |
         echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
         docker push quay.io/lumarel/ee-lint:${{ github.event.release.tag_name }}-stable-2.11
         docker push quay.io/lumarel/ee-lint:stable-2.11

  release-stable-2_12:
    runs-on: ubuntu-latest
    name: Release Ansible 2.12
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker-stable-2.12 -- --tag=quay.io/lumarel/ee-lint:stable-2.12

      - name: Apply latest tag
        run: |
         docker tag quay.io/lumarel/ee-lint:stable-2.12 quay.io/lumarel/ee-lint:${{ github.event.release.tag_name }}-stable-2.12

      - name: Push images
        run: |
         echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
         docker push quay.io/lumarel/ee-lint:${{ github.event.release.tag_name }}-stable-2.12
         docker push quay.io/lumarel/ee-lint:stable-2.12

  release-stable-2_13:
    runs-on: ubuntu-latest
    name: Release Ansible 2.13
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker-stable-2.13 -- --tag=quay.io/lumarel/ee-lint:stable-2.13

      - name: Apply latest tag
        run: |
         docker tag quay.io/lumarel/ee-lint:stable-2.13 quay.io/lumarel/ee-lint:${{ github.event.release.tag_name }}-stable-2.13

      - name: Push images
        run: |
         echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
         docker push quay.io/lumarel/ee-lint:${{ github.event.release.tag_name }}-stable-2.13
         docker push quay.io/lumarel/ee-lint:stable-2.13
